@startuml
skin rose
hide footbox
actor User

participant "Web Browser" as Browser
participant "Custom Web Server" as Server
database "XML Data Storage" as Storage

User -> Browser : Request information
Browser -> Server : HTTP request with query parameters
Server -> Storage : XPath query
Storage --> Server : XML data
Server -> Server : Process and transform XML data
Server --> Browser : HTTP response with data snippet
Browser --> User : Display data snippet
@enduml